---

- name: Download CLI configuration.
  connection: httpapi
  delegate_to: "{{ inventory_hostname }}"
  fortinet.fortiweb.fwebos_backup_download:
    action: get
    type: cli
    filename: "{{ fortiweb_backup_tmp_dir }}/{{ inventory_hostname }}.zip"

- name: Zip all the files.
  connection: local
  community.general.archive:
    path: "{{ fortiweb_backup_tmp_dir }}/*.zip"
    dest: "{{ fortiweb_backup_tmp_dir }}/{{ fortiweb_backup_timestamp }}{{ fortiweb_backup_files_suffix }}.zip"
    mode: "755"
    format: zip
  run_once: true
