---

name: Release to Ansible Galaxy.
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # checkout repo.
      - name: Checkout repository.
        uses: actions/checkout@v4
      # Debug directory structure.
      - name: List current files structure.
        run: |
          sudo apt-get install -y tree
          tree .
      # push to Ansible Galaxy.
      - name: Set up Python 3.
        uses: actions/setup-python@v5
      - name: Install Ansible.
        run: pip3 install ansible-core
      - name: Import role to Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.galaxy_api_key }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
